@startuml
class NavigationMenuViewComponent {
    - repository : IPlatformRepository
    + NavigationMenuViewComponent(repo:IPlatformRepository)
    + Invoke() : IViewComponentResult
}
ViewComponent <|-- NavigationMenuViewComponent
@enduml
