@startuml
!include .\\CourseProject\Program.puml
!include .\\CourseProject.Tests\HomeControllerTest.puml
!include .\\CourseProject.Tests\NavigationMenuViewComponentTests.puml
!include .\\CourseProject.Tests\PageLinkTagHelperTests.puml
!include .\\CourseProject.Tests\Usings.puml
!include .\\CourseProject\Components\NavigationMenuViewComponent.puml
!include .\\CourseProject\Controllers\AccountController.puml
!include .\\CourseProject\Controllers\AdController.puml
!include .\\CourseProject\Controllers\AdminController.puml
!include .\\CourseProject\Controllers\HomeController.puml
!include .\\CourseProject\Infrastructure\PageLinkTagHelper.puml
!include .\\CourseProject\Migrations\20231217145221_Initial.puml
!include .\\CourseProject\Migrations\20231217145221_Initial.Designer.puml
!include .\\CourseProject\Migrations\PlatformDbContextModelSnapshot.puml
!include .\\CourseProject\Models\Ad.puml
!include .\\CourseProject\Models\AppIdentityDbContext.puml
!include .\\CourseProject\Models\Category.puml
!include .\\CourseProject\Models\CustomUserValidator.puml
!include .\\CourseProject\Models\EFPlatformRepository.puml
!include .\\CourseProject\Models\IdentitySeedData.puml
!include .\\CourseProject\Models\IPlatformRepository.puml
!include .\\CourseProject\Models\PlatformDbContext.puml
!include .\\CourseProject\Models\SeedData.puml
!include .\\CourseProject\Migrations\AppIdentityDb\20231215145742_Initial.puml
!include .\\CourseProject\Migrations\AppIdentityDb\20231215145742_Initial.Designer.puml
!include .\\CourseProject\Migrations\AppIdentityDb\AppIdentityDbContextModelSnapshot.puml
!include .\\CourseProject\Models\ViewModels\AdsListViewModel.puml
!include .\\CourseProject\Models\ViewModels\AdViewModel.puml
!include .\\CourseProject\Models\ViewModels\ErrorViewModel.puml
!include .\\CourseProject\Models\ViewModels\PageInfo.puml
!include .\\CourseProject\Models\ViewModels\SignInModel.puml
!include .\\CourseProject\Models\ViewModels\SignUpModel.puml
!include .\\CourseProject\Models\ViewModels\UsersManagerViewModel.puml
!include .\\CourseProject\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\CourseProject\obj\Debug\net7.0\CourseProject.AssemblyInfo.puml
!include .\\CourseProject\obj\Debug\net7.0\CourseProject.GlobalUsings.g.puml
!include .\\CourseProject\obj\Debug\net7.0\CourseProject.RazorAssemblyInfo.puml
!include .\\CourseProject.Tests\obj\Debug\net7.0\.NETCoreApp,Version=v7.0.AssemblyAttributes.puml
!include .\\CourseProject.Tests\obj\Debug\net7.0\CourseProject.Tests.AssemblyInfo.puml
!include .\\CourseProject.Tests\obj\Debug\net7.0\CourseProject.Tests.GlobalUsings.g.puml
@enduml
